backend:
  name: git-gateway
  branch: main

media_folder: "images/products"
public_folder: "/images/products"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
